name = "mastra-chat-cf"
main = ".mastra/output/index.mjs"
compatibility_date = "2024-04-01"
compatibility_flags = ["nodejs_compat", "nodejs_compat_populate_process_env"]

[build]
command = "npm run build"
watch_dir = ".mastra/output"

[env.production]
name = "mastra-chat-cf"
