name = "mastra-chat-cf"
main = ".mastra/output/index.mjs"
compatibility_date = "2024-09-27"
compatibility_flags = ["nodejs_compat", "nodejs_compat_populate_process_env"]

[build]
command = "npm run build"
watch_dir = ".mastra/output"

[env.production]
name = "mastra-chat-cf"

# KV 存储配置
# [[kv_namespaces]]
# binding = "MASTRA_MEMORY"
# id = "your-kv-namespace-id"  # 需要替换为实际的 KV namespace ID
